# The URL the site will be built for
base_url = "https://www.lkoskela.fi"

title = "Lauri Koskela"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "simple-dev-blog"

taxonomies = [ { name = "tags" } ]

generate_feed = true

[languages.fi]
generate_feed = false
title = "Lauri Koskela"

[slugify]
paths_keep_dates = true


[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "1337", filename = "syntax-theme-dark.css" },
  { theme = "material-light", filename = "syntax-theme-light.css" },
]

[extra]
# Put all your custom variables here
dark_mode = true
nav = [ { name = "About", path = "/about/" } ]
accent = "#1683ac"
accent_highlight = "#146887"
accent_light = "#6c8f9d"
dark_mode_accent = "#52b3d8"
dark_mode_accent_highlight = "#66c4e8"
footer_about = "Lauri Koskela // [github.com/luryus](https://github.com/luryus)"